# Generated by Django 3.2.7 on 2021-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('address2', models.TextField()),
                ('City_Village', models.CharField(max_length=122)),
                ('dic', models.CharField(max_length=122)),
                ('atta', models.TextField()),
                ('zip', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
